# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI & Test

on:
  push:
    branches: [master]
  schedule:
    - cron: 0 7 * * SUN

# These permissions are needed to interact with GitHub's OIDC Token endpoint.
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: build-deploy-test
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      - name: Deploy
        run: npm run deploy
      # - name: Run E2E tests
      #   run: npm run test:e2e
      #   env:
      #     NODE_ENV: dev
      # - name: Tear down App stack
      #   run: npm run teardown:app
      # - name: Tear down infrastructure stack
      #   run: npm run teardown:infra
